on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: macOS-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Swift
        uses: actions/setup-swift@v2
        with:
          swift-version: '5.4'

      - name: Build and Test
        run: |
          swift build
          swift test --enable-code-coverage
