on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Run Tests
    runs-on: macOS-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: "Select the latest stable Xcode 14.3.1"
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          project: Arkus.xcodeproj
          destination: platform=iOS
          action: test
      - name: Build
        working-directory: Arkus/
        run: swift build
      - name: Run Test
        working-directory: Arkus/
        run: xcodebuild test -project Arkus.xcodeproj -scheme Arkus -sdk iphonesimulator16.2 -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2'
