on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Run Tests
    runs-on: macOS-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.3.1.app && /usr/bin/xcodebuild -version
      - name: Build and Test
        working-directory: Arkus/
        run: |
          swift build
          xcodebuild test -project Arkus.xcodeproj -scheme Arkus -sdk iphonesimulator16.4 -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4'
